language: node_js
node_js:
    - "node"
before_script:
    - npm install -g gulp-cli
script:
    - yarn run test
    - gulp build
notifications:
    email:
        on_success: never
        on_failure: always
